// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCerVqtMUIcPQTA5mXSPUk2FRGDS_GAuZ0',
    appId: '1:600898880212:android:f63aa31ac7bb546e41b141',
    messagingSenderId: '600898880212',
    projectId: 'taubatexas-37c12',
    databaseURL: 'https://taubatexas-37c12-default-rtdb.firebaseio.com',
    storageBucket: 'taubatexas-37c12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwhO_wzHNEFy5zjF1frzseOhjWKrwnrSM',
    appId: '1:600898880212:ios:a2327596643fec9541b141',
    messagingSenderId: '600898880212',
    projectId: 'taubatexas-37c12',
    databaseURL: 'https://taubatexas-37c12-default-rtdb.firebaseio.com',
    storageBucket: 'taubatexas-37c12.appspot.com',
    iosBundleId: 'com.example.taubatexasApp',
  );
}
